server:
    port: 8084 #El 8761 es el puerto para servidor Eureka por defecto
eureka:
    instance:
      hostname: localhost
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    client:
      registerWithEureka: false
      fetchRegistry: false